### ISSUE TITLE
AdzerkSDK requestPlacements method returns response in a worker thread

### ISSUE THREAD

**Issue by AnttiLaitinenVincit** [adzerk/adzerk-ios-sdk#10]
The SDK seems to return results in a worker thread rather than the main thread. This is dangerous because it can cause e.g. race-conditions in non-threadsafe code (like the UI code) if the developer is unaware of this.

Code example:
```swift
let sdk = AdzerkSDK()
let placements: [ADZPlacement] = [ /* items */ ]

print(Thread.current) // prints main thread

sdk.requestPlacements(placements) { response in
  print(Thread.current) // prints worker thread
}
```

Currently a workaround is to wrap the completion handler with DispatchQueue.main.async to switch back to the main thread.

**Comment by subdigital** [comment]
I apologize for not seeing this sooner.

I agree, this is probably the most common use case for this type of request anyway. I've updated the SDK to version [1.0.2](https://github.com/adzerk/adzerk-ios-sdk/tree/1.0.2) which includes this change, as well as a way to specify your own queue in the initializer, should you need to.

I've also updated the podspec with this new version.

Thanks for reporting the issue!
