### ISSUE TITLE
Support for Swift 4 Codable

### ISSUE THREAD

**Issue by Gabriel-Lewis** [adzerk/adzerk-ios-sdk#13]
Using Codable would be an improvement over parsing through all of the dictionaries in `ADZPlacement`, `ADZPlacementContent`, `ADZPlacementEvent`, etc.

**Comment by subdigital** [comment]
This would be a great addition, however the project also supports Objective-C. At some point we’ll probably make a Swift only version of this, but that’s not currently planned.
