### ISSUE TITLE
Use Adzerk "e-dash" domains

### ISSUE THREAD

**Issue by karnowski** [adzerk/adzerk-ios-sdk#15]
## Background
For operational, performance, and data privacy concerns, Adzerk has migrated customers from the old default Decision and UserDB APIs hostname, `engine.adzerk.net`, onto individual URLs based on their network ID.

The new "e-dash" style URLs look like:  
`e-[networkid].adzerk.net`

For example, the demo network, `23`, uses the URL:
`e-23.adzerk.net`

## Acceptance Criteria

- The SDK no longer uses the `engine.adzerk.net` default.
- The default URL's hostname is now based on a top-level network ID passed in during initialization.
- The default hostname follows the "e-dash" pattern: `e-[networkid].adzerk.net`
- An integrating developer can explicitly override the hostname.  In this case the "e-dash" hostname is ignored.

## Tech Notes

Note that you can still set a network ID on the individual placements, although in practice no one really does this.  If they do, however, then the top-level request still needs to go to one and only one "e-dash" domain host.  So we'll need to add a top-level network ID that determines the host.  The new Decision SDKs (Java, JavaScript, Ruby, Python) also use that top-level on the placement level if it's not explicitly set.  It'd be nice to follow that approach here as well, but it is not strictly required.

There's already a top-level `networkId`, but it appears optional?  We'll need to make it non-optional.  If this requires a breaking change that is okay.  It'll just need to be documented

**Comment by karnowski** [comment]
Also, I'm assuming that no cookies or other "local storage" will be disrupted by this URL change, right?

**Comment by subdigital** [comment]
> Also, I'm assuming that no cookies or other "local storage" will be disrupted by this URL change, right?

Correct
