### ISSUE TITLE
Extra targeting properties for ADZPlacement are not serialized

### ISSUE THREAD

**Issue by AnttiLaitinenVincit** [adzerk/adzerk-ios-sdk#2]
ADZPlacement.serialize() method (ADZPlacement.swift) does not serialize the "properties" property which we use for additional ad targeting. On Android those properties work.

**Comment by karnowski** [comment]
@AnttiLaitinenVincit Thanks for bringing this to our attention!  

Also, can you please email me at larry@adzerk.com so I can ask you some non-open-source questions?  Will help resolve this open-source issue.  Thanks!

**Comment by karnowski** [comment]
Thanks for the pull request @AnttiLaitinenVincit !  We'll get it merged in, deployed, and then we'll close this issue.  (CC @daveyarwood @jcswart @jgrimes)
