### ISSUE TITLE
Stop sending the `time` param on all requests

### ISSUE THREAD

**Issue by karnowski** [adzerk/adzerk-ios-sdk#22]
## Background

The `time` parameter is actually a debugging and testing tool that is no longer a documented feature of Adzerk.  It may be phased out at any time.  However, both the iOS & Android SDKs are sending it on all requests.  Unless there's a really good reason to send it (is there?) then we should remove this unnecessary and potentially error-inducing parameter.

## Acceptance Criteria

- The `time` param is no longer sent on iOS SDK requests.

**Comment by subdigital** [comment]
This one can probably be closed, as I did not add this parameter to the work in the 2.0 branch. You can verify this [here](https://github.com/adzerk/adzerk-ios-sdk/blob/swift-package/Sources/AdzerkSDK/PlacementRequest.swift).
