### ISSUE TITLE
Retrieving the user key from the keychain is nil every time

### ISSUE THREAD

**Issue by tyten** [adzerk/adzerk-ios-sdk#6]
This is caused by the user key being saved to a key of the same name as the value it is trying to store. I have a PR open that addresses this issue.

https://github.com/adzerk/adzerk-ios-sdk/pull/5

**Comment by daveyarwood** [comment]
@tyten Version 0.4 (which includes your fix) is now available via CocoaPods/Carthage. Would you mind testing it to confirm that the user key is saving correctly now?
