### ISSUE TITLE
Any plans for Swift 3 support?

### ISSUE THREAD

**Issue by AnttiLaitinenVincit** [adzerk/adzerk-ios-sdk#7]
This framework no longer builds with XCode 8+ when using Swift 3. Do you have any plans on converting to Swift 3  soon?

**Comment by karnowski** [comment]
@AnttiLaitinenVincit we'll be investigating this soon and will reply with a firmer date as we have one!  Thanks for asking!

**Comment by karnowski** [comment]
This was pushed out last night.  Thanks for the feedback!
